### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sloppily** [maxtheaxe/youtube-handles#3]
F:\youtube-handles-main>python handle_search.py successfully imported 13243 usernames from usernames.csv using latest HAR file: F:\youtube-handles-main\www.youtube.com_Archive [22-11-06 20-56-12].har no session found Traceback (most recent call last): File "F:\youtube-handles-main\handle_search.py", line 174, in <module> main() File "F:\youtube-handles-main\handle_search.py", line 158, in main results, status = run_full_search(usernames, log) File "F:\youtube-handles-main\handle_search.py", line 123, in run_full_search url, headers, payload = import_request(latest_har, (not session_existed), log) File "F:\youtube-handles-main\handle_search.py", line 69, in import_request loads(target_request.request["postData"]["text"]) File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\haralyzer\mixins.py", line 30, in __getitem__ return self.raw_entry[item] KeyError: 'postData'

**Comment by maxtheaxe** [comment]
I just experimented with a few different scenarios that I thought could cause such an issue and none of them produced that error. Do me a favor and retry the HAR saving process (with Firefox, follow along with the video), try to make sure you only save one request when you do so. If that doesn't work, I may need to ask you to upload a (redacted) version of your HAR file, so I can figure out what's going wrong.

**Comment by maxtheaxe** [comment]
Closing this as inactive. If and when you want more help with this, please feel free to re-open it.
